//because windows sucks...

#ifndef PROGRAMCONFIGQTSO_CROSSPLATFORMMACROS_HPP
#define PROGRAMCONFIGQTSO_CROSSPLATFORMMACROS_HPP

#include <QtCore/QtGlobal>

//remember to define this variable in the .pro file
#if defined(PROGRAMCONFIGQTSO_LIBRARY)
#  define EXPIMP_PROGRAMCONFIGQTSO Q_DECL_EXPORT
#else
#  define EXPIMP_PROGRAMCONFIGQTSO Q_DECL_IMPORT
#endif

#endif // ESSENTIALQTSO_CROSSPLATFORMMACROS_HPP
